### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by rishanshah** [adamgibbons/ics#114] opened 2019-07-01 12:09 UTC
I have tried both 
- timezone : 'Europe/london'
- startType: '00:00'

in the creation of the event. from issue #113 

Neither have worked. My the time seems to sync with my calendar subscription 1h after. Please advise on how this can rectify this

code in question:
`  eventsArr.push({
              productId: 'Oshwal',
              startType: '00:00',
              title: $(this).find('.ai1ec-popup-title').text().trim(),
              start: [dateArr[2],dateArr[1],dateArr[0],parseInt(amPm(startTime)[0]),parseInt(amPm(startTime)[1])],
              end: [dateArr[2],dateArr[1],dateArr[0],parseInt(amPm(endTime)[0]),parseInt(amPm(endTime)[1])],
              description: descriptionstr
              })`

**Comment by jcaron23** [comment] 2019-07-01 12:40
Which version of the module are you using? The current published version can take two values for startType:
* 'utc' (default) means you should provide the date/time as UTC, and it will output an UTC time in the event
* 'local' means you provide a date/time that will be output as "floating" (i.e. taken as a literal date/time ignoring the timezone, so people in different time zones will see the same date/time, but it's not the same moment in time).

I recommend you either revert to a previous version, which used local time and converted that to a fixed UTC time, or use my fork https://github.com/jcaron23/ics.git#fix-date-handling until this is fixed in the master branch.

**Comment by rishanshah** [comment] 2019-07-01 12:44
I am using 2.13.2.

I tried using both local and utc and neither seem to work. I am not sure if uct takes into account daylight savings changes. (ie if I have an event for 7am set to utc will it become 8am?)


which previous version should I download?

**Comment by jcaron23** [comment] 2019-07-01 13:12
By definition UTC does not include any time zone or dailyight savings time. You would need to convert your local time to UTC first. For 8am local time in London at this time you would need to set 7am UTC.

Version 2.12 should be OK.

**Comment by jcaron23** [comment] 2019-07-01 13:12
This is a duplicate of #108

**Comment by rishanshah** [comment] 2019-07-01 13:23
How does this work from a server perspective serving multiple countries with different time zones? I read somewhere that there was a timezone parameter in the creation of the event. I tried it but it didn't work? Can you advise on this?

**Comment by jcaron23** [comment] 2019-07-01 13:53
The timezone parameter is in a PR which has not been merged yet (#112). But that timezone comes without the timezone definition, so it's not compliant with the RFC and some clients may not understand.

With the current release, you have to convert from whatever time zone you are using to UTC before giving the data to `createEvent`. In previous releases, `createEvent` would do the conversion for you (using the default current time zone). In PR #113 you have the choice.

**Comment by rishanshah** [comment] 2019-07-02 13:42
Rolled back to 2.12 - this works locally however when deployed into heroku (which I presume has a different system time) the calendar is still 1h off

**Comment by adamgibbons** [comment] 2019-07-04 16:32
Addressed by #115

**Closed by adamgibbons** 2019-07-04 16:32 UTC
