### ISSUE TITLE
Module not found Error: Can't resolve 'dns' 

### ISSUE THREAD

**Issue by dlarr** [adamgibbons/ics#38] opened 2017-11-03 15:38 UTC
Hello, 

I am trying to use this library (many thanks by the way)

But as soon as I use the function ics.createEvent() I get a transpile error (see below)

Could you please help me overcome this.

Best regards.

ERROR in ./node_modules/isemail/lib/index.js
Module not found: Error: Can't resolve 'dns' in 'C:\_dev\nsi\colibri\client\node_modules\isemail\lib'
resolve 'dns' in 'C:\_dev\nsi\colibri\client\node_modules\isemail\lib'
  Parsed request is a module
  using description file: C:\_dev\nsi\colibri\client\node_modules\isemail\package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: C:\_dev\nsi\colibri\client\node_modules\isemail\package.json (relative path: ./lib)
    resolve as module
      C:\_dev\nsi\colibri\client\node_modules\isemail\lib\node_modules doesn't exist or is not a directory
      C:\_dev\nsi\colibri\client\node_modules\isemail\node_modules doesn't exist or is not a directory
      C:\_dev\nsi\colibri\client\node_modules\node_modules doesn't exist or is not a directory
      C:\_dev\nsi\node_modules doesn't exist or is not a directory
      C:\_dev\node_modules doesn't exist or is not a directory
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\_dev\nsi\colibri\client\node_modules
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\node_modules\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\node_modules
        using description file: C:\_dev\nsi\colibri\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\package.json (relative path: ./node_modules)
          using description file: C:\_dev\nsi\colibri\package.json (relative path: ./node_modules/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\node_modules\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\node_modules\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\node_modules\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\node_modules\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\node_modules
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./node_modules/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\node_modules\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\node_modules\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
      looking for modules in C:\_dev\nsi\colibri\client\src
        using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src)
          using description file: C:\_dev\nsi\colibri\client\package.json (relative path: ./src/dns)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.ts doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\_dev\nsi\colibri\client\src\dns.js doesn't exist
            as directory
              C:\_dev\nsi\colibri\client\src\dns doesn't exist
[C:\_dev\nsi\colibri\client\node_modules\isemail\lib\node_modules]
[C:\_dev\nsi\colibri\client\node_modules\isemail\node_modules]
[C:\_dev\nsi\colibri\client\node_modules\node_modules]
[C:\_dev\nsi\node_modules]
[C:\_dev\node_modules]
[C:\node_modules]
[C:\_dev\nsi\colibri\client\node_modules\dns]
[C:\_dev\nsi\colibri\node_modules\dns]
[C:\_dev\nsi\colibri\client\node_modules\dns.ts]
[C:\_dev\nsi\colibri\node_modules\dns.ts]
[C:\_dev\nsi\colibri\client\node_modules\dns.js]
[C:\_dev\nsi\colibri\node_modules\dns.js]
[C:\_dev\nsi\colibri\client\node_modules\dns]
[C:\_dev\nsi\colibri\node_modules\dns]
[C:\_dev\nsi\colibri\client\node_modules\dns]
[C:\_dev\nsi\colibri\client\node_modules\dns.ts]
[C:\_dev\nsi\colibri\client\node_modules\dns.js]
[C:\_dev\nsi\colibri\client\node_modules\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns]
[C:\_dev\nsi\colibri\client\src\dns.ts]
[C:\_dev\nsi\colibri\client\src\dns.js]
[C:\_dev\nsi\colibri\client\src\dns]
 @ ./node_modules/isemail/lib/index.js 5:12-26
 @ ./node_modules/joi/lib/types/string/index.js
 @ ./node_modules/joi/lib/index.js
 @ ./node_modules/ics/dist/schema/index.js
 @ ./node_modules/ics/dist/pipeline/validate.js
 @ ./node_modules/ics/dist/pipeline/index.js
 @ ./node_modules/ics/dist/index.js
 @ ./node_modules/ics/index.js
 @ ./src/app/shared/service/tools.service.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

**Comment by adamgibbons** [comment] 2017-11-07 04:57
Hi @dlarr - it seems as though you're referencing a module `dns` that node can't find. Did you include it in your `package.json`? I am not familiar with your project or the Windows environment, but I don't believe your issue is related to the `ics` project so I'm closing this issue. Sorry I can't be of more help and good luck!

**Comment by dlarr** [comment] 2017-11-07 07:46
Hi, 

I really think there's a dependency problem, realted to isemail, using dns. This error only occurs when I use ics, and ics librairy methods. We had to move on and we used ics-js lib instead, which is a shame because your lib is a lot easier and nicer to use. I didnt want to add dns librairy in package.json because i have no use for it.

Anyway, thank for your reply and your time :)

Best regards.

**Comment by AaronKow** [comment] 2018-02-20 16:23
Hi,
I have similar issue when I tried to use this package in one of my project with Webpack.
As I refer from the module "joi", some dev have similar issue [#665](https://github.com/hapijs/joi/issues/665). 
Luckily, the issue can be resolved by stub the modules by:
```javascript
node: {
    dns: 'empty',
    net: 'empty'
}
```
p.s: I have included `net`, because it can't resolve in that same project.

**Comment by adamgibbons** [comment] 2018-02-20 16:47
Thanks - will take a look.

**Comment by imakatman** [comment] 2018-07-09 19:10
Any update on this?

**Comment by oskari** [comment] 2018-10-22 12:10
This problem is resolved on isemail 3.x already and Joi has already updated their package.json year ago, the problem is ics depending on old version of Joi.

**Closed** 2018-10-29 17:00 UTC

**Comment by FauricioValencia** [comment] 2020-06-25 05:41
the steps of this link work for me:
 https://stackoverflow.com/questions/51541561/module-not-found-cant-resolve-dns-in-pg-lib/51781959

**Comment by AnithaYerra** [comment] 2020-09-11 08:43
doing npm update helps me to resolve this issue
